language: ruby

rvm:
  - 2.2
  - 2.3
  - jruby
  - rbx-2

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile

script: 
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rspec
  - bundle exec rubocop

notifications:
  email: false
  slack:
    rooms:
      secure: OOKD4ZksqzEBW/A3WRuOToODIxnDITqx+Esu7tdmmYPuQlMYgx4SUHv8j9OM9/ScFJiseeVGSkl45vJrHLLIITX9XSjO1RgiGZgw2heVujmGpF6CZNqvT6GsQuKIvMzmwF7IxuHdfV45Csr9Ou/Fg74TszR/4S2h4SOI4zhLg7A=
    on_success: never
